name: biometric_access
description: "The Biometric Access Plugin enables biometric-based authentication with seamless integration of different biometric devices"
version: 0.0.1
homepage: https://github.com/SureshKumar311/flutter_biometric_access_plugin.git

environment:
  sdk: ^3.4.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.0
  plugin_platform_interface: ^2.0.2
  xml2json: ^6.2.3
  universal_io: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  plugin:
    platforms:
      android:
        package: sureshkumar311.com.biometric_access
        pluginClass: BiometricAccessPlugin
      web:
        pluginClass: BiometricAccessWeb
        fileName: biometric_access_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #